package ai.myaba.service;

import ai.myaba.util.FirestoreCollections;

import ai.myaba.model.dto.AclxResponse;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.Firestore;
import com.google.firebase.cloud.FirestoreClient;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Persists AI-generated documents to Firestore alongside their ACLX governance
 * label and signed content passport.
 *
 * <p>Storage path: {@code orgs/{orgId}/clients/{clientId}/documents/{docId}}
 *
 * <p>Each document record stores:
 * <ul>
 *   <li>Document content (final, post-redaction text)</li>
 *   <li>Document type (BIP, FBA, session_note, progress_report, etc.)</li>
 *   <li>ACLX content_id — links to the ACLX audit record</li>
 *   <li>Signed content label (JWS) — chain-of-custody artefact; null when label signing disabled</li>
 *   <li>ACLX decision — ALLOW | REDACT; BLOCK and ESCALATE are never persisted as documents</li>
 *   <li>Sensitivity classification — from the ACLX label (LOW | MEDIUM | HIGH | CRITICAL)</li>
 *   <li>Policy version — OPA bundle version used to make the decision</li>
 *   <li>Redaction count — number of tokens redacted; 0 on ALLOW</li>
 *   <li>Author UID, created timestamp</li>
 * </ul>
 *
 * <p>The write is async so it never blocks the API response path.
 * Document ID is generated by Firestore (auto-ID) and returned via the
 * {@link DocumentReference} future — callers receive the ID synchronously
 * when {@link #persistSync} is used, or asynchronously when {@link #persist} is used.
 */
@Service
@Slf4j
public class DocumentPersistenceService {

    @Value("${dev.auth-enabled:false}")
    private boolean devMode;

    private final DocumentFormatService documentFormatService;
    private final GcsStorageService gcsStorageService;

    public DocumentPersistenceService(DocumentFormatService documentFormatService,
                                      GcsStorageService gcsStorageService) {
        this.documentFormatService = documentFormatService;
        this.gcsStorageService = gcsStorageService;
    }

    /**
     * Persist a generated document synchronously and return its Firestore document ID.
     * Used by the document generation endpoint so the ID can be included in the response.
     *
     * @param orgId       org that owns the document
     * @param clientId    client this document relates to
     * @param authorUid   UID of the clinician who generated the document
     * @param documentType document type slug (e.g. "behavior_intervention_plan")
     * @param content     final document text (post-ACLX, post-redaction)
     * @param aclxResult  full ACLX evaluation result for this document
     * @return Firestore document ID; "dev-doc" in devMode; null on error
     */
    public String persistSync(String orgId, String clientId, String authorUid,
                              String documentType, String content, AclxResponse aclxResult) {
        if (devMode) {
            log.info("[DOC-DEV] persist: org={} client={} type={} contentId={}",
                    orgId, clientId, documentType,
                    aclxResult != null ? aclxResult.getContentId() : "null");
            return "dev-doc-" + java.util.UUID.randomUUID().toString().substring(0, 8);
        }

        try {
            Map<String, Object> doc = buildDocumentRecord(
                    orgId, clientId, authorUid, documentType, content, aclxResult);

            Firestore db = FirestoreClient.getFirestore();
            DocumentReference ref = db
                    .collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS)
                    .add(doc)
                    .get(); // wait for Firestore to assign the ID

            log.info("Document persisted: org={} client={} docId={} contentId={}",
                    orgId, clientId, ref.getId(),
                    aclxResult != null ? aclxResult.getContentId() : "null");
            return ref.getId();

        } catch (Exception e) {
            log.error("Failed to persist document: org={} client={} error={}",
                    orgId, clientId, e.getMessage());
            return null;
        }
    }

    /**
     * Async variant — fire-and-forget.  Used when the document ID is not needed
     * in the immediate response (e.g. updating an existing draft).
     */
    @Async
    public void persist(String orgId, String clientId, String authorUid,
                        String documentType, String content, AclxResponse aclxResult) {
        persistSync(orgId, clientId, authorUid, documentType, content, aclxResult);
    }

    /**
     * Load a client's stored documents (uploaded + AI-generated) for use as chat
     * context and ACLX grounding sources, newest first, capped by count and a
     * total character budget so a document-heavy client can't blow the prompt.
     *
     * <p>Returns entries of {@code {id, title, content}}. Callers must have
     * already verified the user can access this client.
     */
    public List<Map<String, Object>> loadClientContextDocs(String orgId, String clientId,
                                                           int maxDocs, int charBudget) {
        List<Map<String, Object>> out = new ArrayList<>();
        if (devMode) return out;
        try {
            Firestore db = FirestoreClient.getFirestore();
            var docs = db.collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS)
                    .orderBy("createdAtMs", com.google.cloud.firestore.Query.Direction.DESCENDING)
                    .limit(Math.max(1, maxDocs))
                    .get().get().getDocuments();

            int budget = charBudget;
            for (var doc : docs) {
                String content = doc.getString("content");
                if (content == null || content.isBlank()) continue;
                String title = doc.getString("title");
                if (title == null || title.isBlank()) {
                    title = doc.getString("documentType");
                    if (title == null || title.isBlank()) title = "Client document";
                }
                if (content.length() > budget) {
                    if (budget < 500) break; // not enough room left to be useful
                    content = content.substring(0, budget) + "\n…[truncated]";
                }
                budget -= content.length();

                Map<String, Object> entry = new HashMap<>();
                entry.put("id",      doc.getId());
                entry.put("title",   title);
                entry.put("content", content);
                out.add(entry);
                if (budget <= 0) break;
            }
        } catch (Exception e) {
            log.warn("loadClientContextDocs failed org={} client={}: {}", orgId, clientId, e.getMessage());
        }
        return out;
    }

    /**
     * Persist a user-UPLOADED client document (Word/PDF/Excel/text — content is
     * the extracted plain text). Same storage tree as AI-generated documents so
     * it appears in the Documents tab, chat context, and the client export.
     *
     * @return Firestore document ID, or null on error
     */
    public String persistUploaded(String orgId, String clientId, String authorUid,
                                  String title, String sourceFilename, String content) {
        if (devMode) {
            log.info("[DOC-DEV] uploaded: org={} client={} title={}", orgId, clientId, title);
            return "dev-doc-" + java.util.UUID.randomUUID().toString().substring(0, 8);
        }
        try {
            Map<String, Object> doc = buildDocumentRecord(
                    orgId, clientId, authorUid, "uploaded_document", content, null);
            doc.put("title", title);
            doc.put("sourceFilename", sourceFilename);
            doc.put("source", "upload");

            Firestore db = FirestoreClient.getFirestore();
            DocumentReference ref = db
                    .collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS)
                    .add(doc)
                    .get();
            log.info("Uploaded document persisted: org={} client={} docId={}", orgId, clientId, ref.getId());
            return ref.getId();
        } catch (Exception e) {
            log.error("Failed to persist uploaded document: org={} client={} error={}",
                    orgId, clientId, e.getMessage());
            return null;
        }
    }

    // ── Async uploaded-document extraction ─────────────────────────────────────

    /**
     * Create a placeholder uploaded-document record with {@code extractionStatus:
     * PROCESSING} and empty content, returning its ID immediately. The heavy text
     * extraction then runs in the background ({@link #finalizeUpload}) and fills in
     * the content — so a large/scanned upload never times the request out. The doc
     * appears in the Documents tab right away with a "Processing" state.
     *
     * @return Firestore document ID, or null on error
     */
    public String createUploadPlaceholder(String orgId, String clientId, String authorUid,
                                          String title, String sourceFilename) {
        if (devMode) return "dev-doc-" + java.util.UUID.randomUUID().toString().substring(0, 8);
        try {
            Map<String, Object> doc = buildDocumentRecord(
                    orgId, clientId, authorUid, "uploaded_document", "", null);
            doc.put("title", title);
            doc.put("sourceFilename", sourceFilename);
            doc.put("source", "upload");
            doc.put("extractionStatus", "PROCESSING");

            Firestore db = FirestoreClient.getFirestore();
            DocumentReference ref = db
                    .collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS)
                    .add(doc).get();
            return ref.getId();
        } catch (Exception e) {
            log.error("createUploadPlaceholder failed org={} client={}: {}", orgId, clientId, e.getMessage());
            return null;
        }
    }

    /**
     * Background extraction for an uploaded client document: run text extraction
     * and fill in the placeholder created by {@link #createUploadPlaceholder}.
     * Called cross-bean so the {@code @Async} proxy applies.
     */
    @Async("extractionExecutor")
    public void finalizeUpload(String orgId, String clientId, String docId,
                               String filename, String contentType, byte[] bytes) {
        if (devMode) return;
        Map<String, Object> update = new HashMap<>();

        // Store the ORIGINAL bytes in GCS (extracted text still goes to Firestore
        // below). Content hash is recorded regardless of GCS, for dedup/integrity.
        update.put("contentHash", GcsStorageService.sha256Hex(bytes));
        update.put("sizeBytes",   (long) bytes.length);
        if (contentType != null && !contentType.isBlank()) update.put("contentType", contentType);
        if (gcsStorageService.isEnabled()) {
            String objectPath = gcsStorageService.clientObjectPath(orgId, clientId, docId, filename);
            if (gcsStorageService.upload(orgId, objectPath, contentType, bytes)) {
                update.put("gcsBucket", gcsStorageService.getBucket());
                update.put("gcsObject", objectPath);
            }
        }

        try {
            String text = documentFormatService.extractText(filename, bytes, true);
            if (text == null || text.isBlank()) {
                update.put("extractionStatus", "FAILED");
                update.put("extractionError", "No readable text found in \"" + filename + "\".");
            } else {
                update.put("content", text);
                update.put("characters", text.length());
                update.put("extractionStatus", "READY");
            }
        } catch (IllegalArgumentException e) {
            update.put("extractionStatus", "FAILED");
            update.put("extractionError", e.getMessage());
        } catch (Exception e) {
            log.error("finalizeUpload extraction failed doc={} file={}: {}", docId, filename, e.getMessage());
            update.put("extractionStatus", "FAILED");
            update.put("extractionError", "Could not read the file.");
        }
        try {
            FirestoreClient.getFirestore()
                    .collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS).document(docId)
                    .set(update, com.google.cloud.firestore.SetOptions.merge()).get();
        } catch (Exception e) {
            log.error("finalizeUpload update failed doc={}: {}", docId, e.getMessage());
        }
    }

    /**
     * Fetch a single client document record (including {@code gcsObject}). Returns
     * null if it doesn't exist. Caller must have already verified client access.
     */
    public Map<String, Object> getDocument(String orgId, String clientId, String docId) {
        if (devMode) return null;
        try {
            var snap = FirestoreClient.getFirestore()
                    .collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS).document(docId)
                    .get().get();
            if (!snap.exists()) return null;
            Map<String, Object> data = new HashMap<>(snap.getData());
            data.put("id", snap.getId());
            return data;
        } catch (Exception e) {
            log.error("getDocument failed org={} client={} doc={}: {}", orgId, clientId, docId, e.getMessage());
            return null;
        }
    }

    /**
     * Delete a client document: removes the GCS original (best-effort) and the
     * Firestore record. Used by the "Undo" affordance and document management.
     * Caller must have already verified WRITE access to the client.
     *
     * @return true if a document was deleted
     */
    public boolean deleteDocument(String orgId, String clientId, String docId) {
        if (devMode) return true;
        try {
            var ref = FirestoreClient.getFirestore()
                    .collection(FirestoreCollections.DOCUMENTS_ROOT).document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS).document(docId);
            var snap = ref.get().get();
            if (!snap.exists()) return false;
            Object gcsObject = snap.get("gcsObject");
            if (gcsObject instanceof String s && !s.isBlank()) {
                gcsStorageService.delete(s);
            }
            ref.delete().get();
            return true;
        } catch (Exception e) {
            log.error("deleteDocument failed org={} client={} doc={}: {}", orgId, clientId, docId, e.getMessage());
            return false;
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private Map<String, Object> buildDocumentRecord(
            String orgId, String clientId, String authorUid,
            String documentType, String content, AclxResponse aclxResult) {

        Instant now = Instant.now();
        Map<String, Object> doc = new HashMap<>();

        doc.put("orgId",        orgId);
        doc.put("clientId",     clientId);
        doc.put("authorUid",    authorUid);
        doc.put("documentType", documentType);
        doc.put("content",      content);
        doc.put("createdAt",    now.toString());
        doc.put("createdAtMs",  now.toEpochMilli());
        doc.put("status",       "active");

        if (aclxResult != null) {
            doc.put("aclxContentId", aclxResult.getContentId());

            // §2: Store signed content label — chain-of-custody artefact.
            // The JWS compact serialisation can be verified independently of ACLX
            // to prove the label was not tampered with after evaluation.
            if (aclxResult.getContentLabel() != null) {
                doc.put("aclxContentLabel", aclxResult.getContentLabel());
            }

            AclxResponse.Decision decision = aclxResult.getDecision();
            if (decision != null) {
                doc.put("aclxDecision",      decision.getDecision());
                doc.put("aclxPolicyVersion", decision.getPolicyVersion());
                List<String> redacted = decision.getRedactedTokens();
                doc.put("aclxRedactionCount", redacted != null ? redacted.size() : 0);
            }

            AclxResponse.AclxLabel label = aclxResult.getAclx();
            if (label != null) {
                doc.put("sensitivity",    label.getSensitivity());
                doc.put("aclxCategory",   label.getCategory());
                doc.put("aclxDomain",     label.getDomain());
                if (label.getAudit() != null) {
                    doc.put("aclxDecisionId", label.getAudit().getDecisionId());
                }
            }

            doc.put("synthesisDetected", aclxResult.isSynthesisDetected());
        }

        return doc;
    }
}
