package ai.myaba.service;

import ai.myaba.util.FirestoreCollections;

import ai.myaba.model.dto.AclxResponse;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.Firestore;
import com.google.firebase.cloud.FirestoreClient;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Persists AI-generated documents to Firestore alongside their ACLX governance
 * label and signed content passport.
 *
 * <p>Storage path: {@code orgs/{orgId}/clients/{clientId}/documents/{docId}}
 *
 * <p>Each document record stores:
 * <ul>
 *   <li>Document content (final, post-redaction text)</li>
 *   <li>Document type (BIP, FBA, session_note, progress_report, etc.)</li>
 *   <li>ACLX content_id — links to the ACLX audit record</li>
 *   <li>Signed content label (JWS) — chain-of-custody artefact; null when label signing disabled</li>
 *   <li>ACLX decision — ALLOW | REDACT; BLOCK and ESCALATE are never persisted as documents</li>
 *   <li>Sensitivity classification — from the ACLX label (LOW | MEDIUM | HIGH | CRITICAL)</li>
 *   <li>Policy version — OPA bundle version used to make the decision</li>
 *   <li>Redaction count — number of tokens redacted; 0 on ALLOW</li>
 *   <li>Author UID, created timestamp</li>
 * </ul>
 *
 * <p>The write is async so it never blocks the API response path.
 * Document ID is generated by Firestore (auto-ID) and returned via the
 * {@link DocumentReference} future — callers receive the ID synchronously
 * when {@link #persistSync} is used, or asynchronously when {@link #persist} is used.
 */
@Service
@Slf4j
public class DocumentPersistenceService {

    @Value("${dev.auth-enabled:false}")
    private boolean devMode;

    /**
     * Persist a generated document synchronously and return its Firestore document ID.
     * Used by the document generation endpoint so the ID can be included in the response.
     *
     * @param orgId       org that owns the document
     * @param clientId    client this document relates to
     * @param authorUid   UID of the clinician who generated the document
     * @param documentType document type slug (e.g. "behavior_intervention_plan")
     * @param content     final document text (post-ACLX, post-redaction)
     * @param aclxResult  full ACLX evaluation result for this document
     * @return Firestore document ID; "dev-doc" in devMode; null on error
     */
    public String persistSync(String orgId, String clientId, String authorUid,
                              String documentType, String content, AclxResponse aclxResult) {
        if (devMode) {
            log.info("[DOC-DEV] persist: org={} client={} type={} contentId={}",
                    orgId, clientId, documentType,
                    aclxResult != null ? aclxResult.getContentId() : "null");
            return "dev-doc-" + java.util.UUID.randomUUID().toString().substring(0, 8);
        }

        try {
            Map<String, Object> doc = buildDocumentRecord(
                    orgId, clientId, authorUid, documentType, content, aclxResult);

            Firestore db = FirestoreClient.getFirestore();
            DocumentReference ref = db
                    .collection("orgs").document(orgId)
                    .collection(FirestoreCollections.CLIENTS).document(clientId)
                    .collection(FirestoreCollections.DOCUMENTS)
                    .add(doc)
                    .get(); // wait for Firestore to assign the ID

            log.info("Document persisted: org={} client={} docId={} contentId={}",
                    orgId, clientId, ref.getId(),
                    aclxResult != null ? aclxResult.getContentId() : "null");
            return ref.getId();

        } catch (Exception e) {
            log.error("Failed to persist document: org={} client={} error={}",
                    orgId, clientId, e.getMessage());
            return null;
        }
    }

    /**
     * Async variant — fire-and-forget.  Used when the document ID is not needed
     * in the immediate response (e.g. updating an existing draft).
     */
    @Async
    public void persist(String orgId, String clientId, String authorUid,
                        String documentType, String content, AclxResponse aclxResult) {
        persistSync(orgId, clientId, authorUid, documentType, content, aclxResult);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private Map<String, Object> buildDocumentRecord(
            String orgId, String clientId, String authorUid,
            String documentType, String content, AclxResponse aclxResult) {

        Instant now = Instant.now();
        Map<String, Object> doc = new HashMap<>();

        doc.put("orgId",        orgId);
        doc.put("clientId",     clientId);
        doc.put("authorUid",    authorUid);
        doc.put("documentType", documentType);
        doc.put("content",      content);
        doc.put("createdAt",    now.toString());
        doc.put("createdAtMs",  now.toEpochMilli());
        doc.put("status",       "active");

        if (aclxResult != null) {
            doc.put("aclxContentId", aclxResult.getContentId());

            // §2: Store signed content label — chain-of-custody artefact.
            // The JWS compact serialisation can be verified independently of ACLX
            // to prove the label was not tampered with after evaluation.
            if (aclxResult.getContentLabel() != null) {
                doc.put("aclxContentLabel", aclxResult.getContentLabel());
            }

            AclxResponse.Decision decision = aclxResult.getDecision();
            if (decision != null) {
                doc.put("aclxDecision",      decision.getDecision());
                doc.put("aclxPolicyVersion", decision.getPolicyVersion());
                List<String> redacted = decision.getRedactedTokens();
                doc.put("aclxRedactionCount", redacted != null ? redacted.size() : 0);
            }

            AclxResponse.AclxLabel label = aclxResult.getAclx();
            if (label != null) {
                doc.put("sensitivity",    label.getSensitivity());
                doc.put("aclxCategory",   label.getCategory());
                doc.put("aclxDomain",     label.getDomain());
                if (label.getAudit() != null) {
                    doc.put("aclxDecisionId", label.getAudit().getDecisionId());
                }
            }

            doc.put("synthesisDetected", aclxResult.isSynthesisDetected());
        }

        return doc;
    }
}
